const Wisdom = [
  'Mongo is a monetary value for Mongolia. ',
  "Let's hope we've created life.",
  'Is electricity a gas or a liquid?',
  'So middleware is like a soup... or like a good stew',
  'How do you keep this nice beard',
  "Silence...  that joke didn't fly",
  'How great is it to be part of the central kingdom?',
  'Do you guys feel like conquistadors?',
  'Why is there christian rock, but not like buddhist synth wave?',
  "Imagine you go to a renaissance fair and it's full of cool kids on tik tok",
  "You know how Asians have good calves? That's from climbing mountains.",
  "Have I told you guys about my metal shirt theory? You just don't really see other shirts.",
  'Mixed nuts are a scam',
  'Imagine suggesting domesticating gorillas and people are like, "You\'re crazy"',
  'I feel like Ragan is tiptoeing into dreamland',
  "the spoon legend, it's bullshit right?",
  'Imagine having a spoon... I just have a bunch of random spoons that belong to my general family\n',
  "Imagine 'making my way downtown', but in Mark's accent... and he's just saying it",
  'You look like an asterisk',
  'Alex just has some giant f***ing boots to stomp people',
  'I heard a gorilla can brush aside 3 strong men like a twig',
  "Who's the first person to put a gorilla in a zoo... What a maniac",
  'Imagine slang was invented by 10 hooded men underground',
  'What is the least conservative British accent',
  'Is the port only open for the pizza guy?',
  'What is like… a belly button\n',
  'What do you think about convention over configuration\n',
  'Whats the tech scene like in North Korea',
  'Expand the monkeysphere',
  'My surname is Ball, but they call me Mr. Ball',
  "I'd rather watch a referee beat up a little girl than two soccer players fighting",
  'People look at the gorilla density and wonder, Who the f*** is this guy?',
  'Please call me Row 4',
  'To make MERN not MEAN',
  'If react uses react to build their site, is that like wearing your own band shirt?',
  'If you could go back in time would you kill Cathy Freeman',
  'You look visibly sterile',
  'I feel like I’m fading away from existence',
  'Imagine having a spoon',
  'I can appreciate my own quotes',
  'I’d love to go to New England in the fall with a f***ing Starbucks pumpkin thing',
  'What is the temperature on the moon?',
  'Can someone do an EB Games sales accent',
  'What do you do?',
  'Imagine Ricky in the 90s',
  'You say root beer and a tear falls down Garrets eye',
  'What is a man',
  'Is there a good tech scene in jail?',
  'If you do bad, you just face assassins in the wasteland',
  'Don’t jump, there’s still so much to live for',
  'Imagine dying at a lunch table surrounded by a bunch of guys and you’re all just making fun of death',
  'Garret should combine his hobbies and make a gun that shoots boardgames',
  'Alex has a dark past... he was in a Christmas cover band',
  'Hawaiian is the Nickelback of pizza',
];

export default Wisdom;
